name: CI

on: [pull_request]
    
jobs:
  setup:
    runs-on: [ubuntu-latest]
    steps:
        - run: npm ci
  lint:
    runs-on: [ubuntu-latest]
    needs: [setup]
    steps:
      - run: npm run lint
           
  test:
    runs-on: [ubuntu-latest]
    needs: [setup]
    steps:
      - run: npm run test -- --ci
